apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
      name: http
    - port: 5000
      targetPort: 5000
      nodePort: 30500
      name: docker
  selector:
    app: nexus