apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
      name: http
    - port: 5001
      targetPort: 5001
      nodePort: 30501
      name: docker-base
    - port: 5002
      targetPort: 5002
      nodePort: 30502
      name: docker-app
  selector:
    app: nexus