apiVersion: batch/v1
kind: CronJob
metadata:
  name: zap-scheduled-scan
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1001
          containers:
            - name: zap-scanner
              image: zaproxy/zap-stable:latest
              securityContext:
                runAsUser: 1000
                runAsGroup: 1001
              command: ["zap-api-scan.py"]
              args:
                - "-t"
                - "http://poc-zap-service/v2/api-docs"
                - "-f"
                - "openapi"
                - "-r"
                - "/zap/wrk/scheduled-$(date +%Y%m%d).html"
                - "-d"
                - "-I"
                - "-z"
                - "-config connection.timeoutInSecs=120"
              env:
                - name: ZAP_JVM_OPTIONS
                  value: "-Xmx2048m -XX:ParallelGCThreads=2"
              resources:
                limits:
                  memory: "4Gi"
                  cpu: "2"
                requests:
                  memory: "2Gi"
                  cpu: "1"
              volumeMounts:
                - name: reports
                  mountPath: /zap/wrk
          volumes:
            - name: reports
              persistentVolumeClaim:
                claimName: zap-reports-pvc
          restartPolicy: Never