apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-viewer
  template:
    metadata:
      labels:
        app: report-viewer
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: reports
              mountPath: /usr/share/nginx/html
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Set permissions for the reports directory
              chmod -R 775 /usr/share/nginx/html && \
              addgroup -g 1001 zapgroup && \
              adduser nginx zapgroup && \
              chown -R :zapgroup /usr/share/nginx/html && \
              chmod -R 775 /usr/share/nginx/html && \
              rm -f /etc/nginx/conf.d/default.conf && \
              # Nginx config (directory listing only)
              cat > /etc/nginx/conf.d/reports.conf <<'NGINX_EOF'
              server {
                  listen 80;
                  server_name _;

                  location / {
                      root /usr/share/nginx/html;
                      autoindex on;
                      autoindex_localtime on;
                      add_header X-Frame-Options "SAMEORIGIN";
                      add_header X-Content-Type-Options "nosniff";
                  }
              }
              NGINX_EOF
              exec nginx -g 'daemon off;'
          ports:
            - containerPort: 80
      volumes:
        - name: reports
          persistentVolumeClaim:
            claimName: reports-pvc