apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-viewer
  template:
    metadata:
      labels:
        app: report-viewer
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: reports
              mountPath: /usr/share/nginx/html
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Install only necessary packages (jq for JSON parsing)
              apk add --no-cache jq && \
              
              # Create simplified comparison script
              cat > /usr/share/nginx/html/compare_reports.sh <<'EOF'
              #!/bin/sh
              set -e
              
              # Find latest reports
              LATEST_ZAP=$(ls -t /usr/share/nginx/html/zap/*.json 2>/dev/null | head -1 || true)
              LATEST_BURP=$(ls -t /usr/share/nginx/html/burp/*.html 2>/dev/null | head -1 || true)
              
              # Count vulnerabilities
              ZAP_COUNT=$([ -n "$LATEST_ZAP" ] && jq '.site[0].alerts | length' "$LATEST_ZAP" || echo 0)
              BURP_COUNT=$([ -n "$LATEST_BURP" ] && grep -c 'issue-type' "$LATEST_BURP" || echo 0)
              
              # Generate comparison JSON
              cat > /usr/share/nginx/html/comparison.json <<COMP_EOF
              {
                "timestamp": "$(date -Is)",
                "reports": {
                  "zap": "$(basename "$LATEST_ZAP" 2>/dev/null || echo null)",
                  "burp": "$(basename "$LATEST_BURP" 2>/dev/null || echo null)"
                },
                "vulnerabilities": {
                  "zap": $ZAP_COUNT,
                  "burp": $BURP_COUNT
                }
              }
              COMP_EOF
              EOF
              
              # Make script executable
              chmod +x /usr/share/nginx/html/compare_reports.sh && \
              
              # Original setup
              addgroup -g 1001 zapgroup && \
              adduser nginx zapgroup && \
              mkdir -p /usr/share/nginx/html/{zap,burp} && \
              chown -R :zapgroup /usr/share/nginx/html && \
              chmod -R 775 /usr/share/nginx/html && \
              rm -f /etc/nginx/conf.d/default.conf && \
              
              # Nginx config
              cat > /etc/nginx/conf.d/reports.conf <<'NGINX_EOF'
              server {
                  listen 80;
                  server_name _;
              
                  location / {
                      root /usr/share/nginx/html;
                      autoindex on;
                      autoindex_localtime on;
                      add_header X-Frame-Options "SAMEORIGIN";
                      add_header X-Content-Type-Options "nosniff";
                  }
              
                  location /compare {
                      alias /usr/share/nginx/html/comparison.json;
                      default_type application/json;
                      add_header Cache-Control "no-store";
                  }
              }
              NGINX_EOF
              
              # Run comparison and start nginx
              /usr/share/nginx/html/compare_reports.sh && \
              chown -R nginx:zapgroup /usr/share/nginx/html && \
              exec nginx -g 'daemon off;'
          ports:
            - containerPort: 80
      volumes:
        - name: reports
          persistentVolumeClaim:
            claimName: zap-reports-pvc