parameters:
  api.disablekey: true

env:
  contexts:
    - name: "Vulnerable API Demo"
      urls:
        - "http://poc-zap-service:9999"

jobs:
  - type: postman
    parameters:
      collectionFile: /zap/wrk/config/postman/postman-collection.json

  - type: script
    parameters:
      action: add
      file: /zap/wrk/config/scripts/httpsender/intercept.js
      type: httpsender
      engine: Graal.js
      name: intercept.js

  - type: script
    parameters:
      action: add
      file: /zap/wrk/config/scripts/httpsender/log_requests.js
      type: httpsender
      engine: Graal.js
      name: log_requests.js

  - type: script
    parameters:
      action: add
      file: /zap/wrk/config/scripts/active/xss.js
      type: active
      engine: Graal.js
      name: xss.js

  - type: spider
    parameters:
      context: "Vulnerable API Demo"
      maxDuration: 60

  - type: activeScan
    parameters:
      context: "Vulnerable API Demo"
      policy: "Default Policy"

  - type: report
    parameters:
      template: "traditional-html"
      reportFile: "__REPORT_HTML__"

  - type: report
    parameters:
      template: "traditional-json"
      reportFile: "__REPORT_JSON__"