apiVersion: batch/v1
kind: Job
metadata:
  name: zap-custom-pen-test
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
        - key: "node.kubernetes.io/unschedulable"
          operator: "Exists"
          effect: "NoSchedule"
      securityContext:
        fsGroup: 1001
      containers:
        - name: zap-scanner
          image: zaproxy/zap-stable:latest
          securityContext:
            runAsUser: 1000
            runAsGroup: 1001
          command: ["sh", "-c"]
          args:
            - |
              mkdir -p /zap/wrk/zap && \
              mkdir -p /tmp/scripts && \
              # Copy scripts to writable /tmp/scripts
              cp /zap/scripts/custom_tests/* /tmp/scripts/ && \
              # Run ZAP with scripts from /tmp/scripts
              zap-baseline.py -t http://poc-zap-service:80/api \
                -r "/zap/wrk/zap/on-demand-pen-test-$(date +%Y%m%d-%H%M).html" \
                -J "/zap/wrk/zap/on-demand-pen-test-$(date +%Y%m%d-%H%M).json" \
                -d -I \
                -z "-config script.scripts=/tmp/scripts/*.zap" \
                --hook /zap/scripts/error_handler.py
          env:
            - name: ZAP_JVM_OPTIONS
              value: "-Xmx1024m -XX:ParallelGCThreads=1"
          resources:
            limits:
              memory: "1.5Gi"
              cpu: "800m"
            requests:
              memory: "512Mi"
              cpu: "300m"
          volumeMounts:
            - name: reports
              mountPath: /zap/wrk
            - name: zap-scripts
              mountPath: /zap/scripts
            - name: custom-tests
              mountPath: /zap/scripts/custom_tests
      volumes:
        - name: reports
          persistentVolumeClaim:
            claimName: zap-reports-pvc
        - name: zap-scripts
          configMap:
            name: zap-scripts
        - name: custom-tests
          configMap:
            name: custom-pen-tests
      restartPolicy: Never