apiVersion: batch/v1
kind: Job
metadata:
  name: zap-custom-pen-test
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
        - key: node.kubernetes.io/unschedulable
          operator: Exists
          effect: NoSchedule
      securityContext:
        fsGroup: 1001
      containers:
        - name: zap-scanner
          image: stefangolubov/zap-with-scripting:latest
          securityContext:
            runAsUser: 1000
            runAsGroup: 1001
          command:
            - sh
            - -c
          args:
            - |
              mkdir -p /zap/wrk/zap && \
              # Optionally list scripts for debug
              ls -l /zap/scripts/shared_tests/ && \
              # Run ZAP Automation Framework plan
              zap.sh -cmd -autorun /zap/scripts/zap-automation.yaml || true
              echo "ZAP finished, entering sleep for debugging"
              sleep 3600
          env:
            - name: ZAP_JVM_OPTIONS
              value: -Xmx1024m -XX:ParallelGCThreads=1
          resources:
            limits:
              memory: 1.5Gi
              cpu: 800m
            requests:
              memory: 512Mi
              cpu: 300m
          volumeMounts:
            - name: reports
              mountPath: /zap/wrk
            - name: zap-scripts-pentest
              mountPath: /zap/scripts
            - name: shared-tests
              mountPath: /zap/scripts/shared_tests
      volumes:
        - name: reports
          persistentVolumeClaim:
            claimName: zap-reports-pvc
        - name: zap-scripts-pentest
          configMap:
            name: zap-scripts-pentest
        - name: shared-tests
          configMap:
            name: custom-pen-tests
      restartPolicy: Never