apiVersion: v1
kind: ConfigMap
metadata:
  name: zap-scripts-pentest
data:
  zap-automation.yaml: |
    env:
      contexts:
        - name: Default Context
          urls:
            - "http://poc-zap-service:80/api/hello"
            - "http://poc-zap-service:80/api/users?id=1"
            - "http://poc-zap-service:80/api/greet?username=test"
            - "http://poc-zap-service:80/api/ping?host=localhost"
            - "http://poc-zap-service:80/api/admin/env"
    jobs:
      - type: script
        parameters:
          action: add
          type: httpsender
          engine: Graal.js
          name: sql_injection_test
          file: /zap/scripts/shared_tests/sql_injection_test.zap
      - type: script
        parameters:
          action: add
          type: httpsender
          engine: Graal.js
          name: xss_test
          file: /zap/scripts/shared_tests/xss_test.zap
      - type: script
        parameters:
          action: add
          type: httpsender
          engine: Graal.js
          name: command_injection_test
          file: /zap/scripts/shared_tests/command_injection_test.zap
      - type: script
        parameters:
          action: add
          type: httpsender
          engine: Graal.js
          name: info_exposure_test
          file: /zap/scripts/shared_tests/info_exposure_test.zap
      - type: script
        parameters:
          action: add
          type: httpsender
          engine: Graal.js
          name: test_minimal
          file: /zap/scripts/shared_tests/test_minimal.zap
      - type: spider
        parameters:
          context: Default Context
          maxDuration: 2
      - type: activeScan
        parameters:
          context: Default Context
      - type: report
        parameters:
          template: traditional-html
          reportDir: /zap/wrk/zap
          reportFile: on-demand-pen-test.html
      - type: report
        parameters:
          template: traditional-json
          reportDir: /zap/wrk/zap
          reportFile: on-demand-pen-test.json