apiVersion: batch/v1
kind: CronJob
metadata:
  name: zap-scheduled-scan
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1001
          containers:
            - name: zap-scanner
              image: zaproxy/zap-stable:latest
              securityContext:
                runAsUser: 1000
                runAsGroup: 1001
              command: ["sh", "-c"]
              args:
                - |
                  mkdir -p /zap/wrk && \
                  mkdir -p /usr/share/nginx/html && \
                  zap-api-scan.py -t http://poc-zap-service/v2/api-docs \
                  -f openapi \
                  -r "/usr/share/nginx/html/scheduled-$(date +%Y%m%d).html" \
                  -d -I
              volumeMounts:
                - name: zap-reports
                  mountPath: /usr/share/nginx/html
              resources:
                limits:
                  memory: "2Gi"
                  cpu: "2"
                requests:
                  memory: "512Mi"
                  cpu: "500m"
          volumes:
            - name: zap-reports
              persistentVolumeClaim:
                claimName: zap-reports-pvc
          restartPolicy: Never