apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap-scanner
  labels:
    app: zap-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zap-scanner
  template:
    metadata:
      labels:
        app: zap-scanner
    spec:
      containers:
        - name: zap
          image: zaproxy/zap-stable:latest
          command: ["zap.sh"]
          args:
            - "-daemon"
            - "-host"
            - "0.0.0.0"
            - "-port"
            - "8080"
            - "-config"
            - "api.disablekey=true"
            - "-config"
            - "api.addrs.addr.name=.*"
            - "-config"
            - "api.addrs.addr.regex=true"
            - "-config"
            - "script.defaultEngine=ECMAScript"
            - "-config"
            - "scripts.console=true"
          ports:
            - containerPort: 8080
          env:
            - name: ZAP_JVM_OPTIONS
              value: "-Xmx2048m -XX:ParallelGCThreads=2"
            - name: ZAP_CONNECTION_TIMEOUT
              value: "120"
            - name: ZAP_SCRIPT_DIRS
              value: "/zap/scripts:/zap/scripts/custom_tests"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
            - name: zap-reports
              mountPath: /zap/wrk
            - name: zap-scripts-pentest
              mountPath: /zap/scripts
            - name: custom-tests
              mountPath: /zap/scripts/custom_tests
      volumes:
        - name: zap-reports
          persistentVolumeClaim:
            claimName: zap-reports-pvc
        - name: zap-scripts-pentest
          configMap:
            name: zap-scripts-pentest
        - name: custom-tests
          configMap:
            name: custom-pen-tests