apiVersion: batch/v1
kind: Job
metadata:
  name: zap-on-demand-scan
spec:
  template:
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: zap-scanner
          image: zaproxy/zap-stable:latest
          securityContext:
            runAsUser: 1000
            runAsGroup: 1001
          command: ["sh", "-c"]
          args:
            - |
              echo "Starting ZAP scan..."
              mkdir -p /zap/wrk && \
              mkdir -p /usr/share/nginx/html && \
              zap-api-scan.py -t http://poc-zap-service/api \
                -f openapi \
                -r "/usr/share/nginx/html/on-demand-$(date +%Y%m%d-%H%M).html" \
                -d
              echo "Scan completed. Report generated."
          volumeMounts:
            - name: reports
              mountPath: /usr/share/nginx/html
          env:
            - name: ZAP_JVM_OPTIONS
              value: "-Xmx512m -XX:ParallelGCThreads=1 -XX:+UseContainerSupport"
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: reports
          persistentVolumeClaim:
            claimName: zap-reports-pvc
      restartPolicy: Never