apiVersion: v1
kind: Service
metadata:
  name: zap-service
  annotations:
    # Add these annotations for better load balancing
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: zap-scanner
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080